<a href="https://colab.research.google.com/github/jescalada/Tensorflow-colabs/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we will cover some fundamental concepts of tensors using TensorFlow 

More specifically, we're going to cover:
* Intro to tensors
* Getting info from tensors
* Manipulating tensors
* Tensors and numpy
* Using @tf.function
* Using GPUs with TF

## Intro to tensors

In [2]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.12.0


In [3]:
# Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Check the number of dimensions of a tensor (ndim - number of dimensions)
scalar.ndim

0

In [5]:
# Create a vector
vector = tf.constant([0,0,255,0,255])
vector

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([  0,   0, 255,   0, 255], dtype=int32)>

In [6]:
vector.ndim

1

In [7]:
matrix = tf.constant([[123, 225],
                      [45, 0]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[123, 225],
       [ 45,   0]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
# Create another matrix
matrix_b = tf.constant([[0.99, 0.01],
                        [0.05, 0.95]], dtype=tf.float16)
matrix_b

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[0.99, 0.01],
       [0.05, 0.95]], dtype=float16)>

In [10]:
matrix_b.ndim

2

In [11]:
# Creating a 3-dim tensor
cube = tf.constant([[
                     [1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]],
                    
                    [[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]],
                    
                    [[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]]])
cube

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]], dtype=int32)>

In [12]:
cube.ndim

3

# Creating tensors with `tf.Variable`

In [13]:
var_tensor = tf.Variable([1, 2, 3])
const_tensor = tf.constant([1, 2, 3])
var_tensor, const_tensor

(<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>)

In [14]:
# Changing the values of a variable tensor
var_tensor = tf.Variable([2, 3, 4])
var_tensor

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([2, 3, 4], dtype=int32)>

In [15]:
var_tensor[0].assign(5)
var_tensor

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([5, 3, 4], dtype=int32)>

In [17]:
# This is not valid!
# const_tensor[0].assign(2)

In [18]:
# Creating random tensors
random_tensor1 = tf.random.Generator.from_seed(123)
random_tensor2 = tf.random.Generator.from_seed(12)
random_tensor3 = tf.random.normal(shape=(3, 1))
random_tensor1, random_tensor2, random_tensor3

(<tensorflow.python.ops.stateful_random_ops.Generator at 0x7f20a496f0a0>,
 <tf.Tensor: shape=(3, 1), dtype=float32, numpy=
 array([[0.39409631],
        [0.4177558 ],
        [0.35466573]], dtype=float32)>)

# Shuffling the order of elements in a tensor

In [ ]:
# Shuffling is useful for mixing up the ordering of the data (to make it pseudorandom)
not_shuffled = tf.random.normal(shape=(3, 1))
shuffled = tf.random.shuffle(not_shuffled)
not_shuffled, shuffled

# Creating tensors filled with certain data

In [19]:
# Create a tensor filled with ones
tf.ones((4, 1))

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[1.],
       [1.],
       [1.],
       [1.]], dtype=float32)>

In [20]:
# Create a tensor filled with zeroes
tf.zeros(shape=(3, 3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [21]:
# Turn numpy arrays into tensors
# Tensors can be run in a GPU, unlike numpy arrays
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)  # create a NumPy array with values [1, 25)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [22]:
# Convert the numpy array into a tensor by passing it into the constructor method (takes a tensor-like object)
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [23]:
# We can change the shape of the data without changing the data itself
B = tf.constant(numpy_A, shape=(3, 4, 2))  # This only works if multiplying the dimensions equals 24
B

<tf.Tensor: shape=(3, 4, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]], dtype=int32)>

# Getting info from tensors:
* Shape: The length (number of elements) of each of the dimensions of a tensor
  * `tensor.shape`
* Rank: The number of tensor dimensions. Scalar -> 0, Vector -> 1, etc.
  * `tensor.ndim`
* Axis/Dimension: A particular dimension of a tensor.
  * `tensor[0]`, `tensor[:,1]`, etc.
* Size: The total number of items in the tensor
  * `tf.size(tensor)`

In [24]:
# Creating a rank 4 tensor
rank4tensor = tf.zeros(shape=[2, 2, 2, 4])
rank4tensor

<tf.Tensor: shape=(2, 2, 2, 4), dtype=float32, numpy=
array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]]], dtype=float32)>

In [25]:
rank4tensor.shape, rank4tensor.ndim, tf.size(rank4tensor)  # Note that tf.size returns a scalar tensor

(TensorShape([2, 2, 2, 4]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=32>)

# Indexing tensors
Tensors can be indexed like Python lists:

In [27]:
# Get the first 2 elements of each dimension
rank4tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [44]:
# Get the first elem from each dimension from each index except the final index
rank4tensor[0, 0, 0, :]

# Create rank 2 tensor
rank2tensor = tf.constant([[1, 2],
                           [3, 4]])

# Get the last item of each row of the tensor:
rank2tensor[:, -1]


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [47]:
# Add an extra dimension at the innermost part of the tensor (individual elements)
rank3tensor = rank2tensor[..., tf.newaxis]  # Ellipsis is for ignoring all the other dimensions (which we don't know)

# Add an extra dimension at the outermost part of the tensor (wraps entire tensor)
another_rank3tensor = rank2tensor[tf.newaxis, ...]

rank3tensor, another_rank3tensor

(<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[1],
         [2]],
 
        [[3],
         [4]]], dtype=int32)>,
 <tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
 array([[[1, 2],
         [3, 4]]], dtype=int32)>)

In [52]:
# Alternative to tf.newaxis
tf.expand_dims(rank2tensor, axis=-1)  # Just expands the last element (in this case, axis = 2 which makes it a rank3tensor)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

# Manipulating Tensors (tensor operations)
### Basic Operations
`+` `-` `*` `/`

In [58]:
tensor = tf.constant([[1, 2],
                      [3, 4]])
tensor + 10, tensor * 10, tensor - 10, tensor / 10


(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[11, 12],
        [13, 14]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10, 20],
        [30, 40]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[-9, -8],
        [-7, -6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=float64, numpy=
 array([[0.1, 0.2],
        [0.3, 0.4]])>)

In [61]:
tensor2 = tf.constant([[5, 4],
                       [3, 2]])
tf.multiply(tensor, tensor2)  # Tensor multiplication is element-wise! NOT like matrix multiplication

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 8],
       [9, 8]], dtype=int32)>

# Matrix multiplication
This is one of the most common operations in Machine Learning

In [64]:
# Matrix multiplication in tensorflow
tf.matmul(tensor, tensor2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11,  8],
       [27, 20]], dtype=int32)>

In [65]:
# Create a (3, 2) tensor and a (2, 3) tensor
tensor32 = tf.constant([[1, 2],
                        [3, 4],
                        [5, 6]])

tensor23 = tf.constant([[6, 4, 2],
                        [5, 3, 1]])

tf.matmul(tensor32, tensor23)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[16, 10,  4],
       [38, 24, 10],
       [60, 38, 16]], dtype=int32)>

# Aggregating Tensors
Aggregating tensors means condensing them from many values to less values

In [69]:
# Get absolute values
D = tf.constant([-1, -2, 3])
tf.abs(D)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

Some forms of aggregation:
* Get the minimum
* Get the maximum
* Get the mean
* Get the sum

In [83]:
# Create a random tensor with values in [0, 100) and size 50
A = tf.constant(np.random.randint(0, 100, size=50))
A

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([69, 22,  7, 77, 42, 89, 50, 84,  5, 92, 85, 74, 13, 14, 51, 19, 11,
       29, 11, 90, 54, 15, 94, 31, 41, 96, 74, 40, 68, 64,  8, 73, 14, 11,
       94, 90,  8, 69, 56, 67, 56, 16, 48, 15, 69, 75, 75,  2, 12, 64])>

In [86]:
# Find the minimum, maximum, mean, sum
tf.reduce_min(A), tf.reduce_max(A), tf.reduce_mean(A), tf.reduce_sum(A)

(<tf.Tensor: shape=(), dtype=int64, numpy=2>,
 <tf.Tensor: shape=(), dtype=int64, numpy=96>,
 <tf.Tensor: shape=(), dtype=int64, numpy=48>,
 <tf.Tensor: shape=(), dtype=int64, numpy=2433>)

In [92]:
# Find the variance and SD
tf.math.reduce_variance(tf.cast(A, dtype=tf.float64)), tf.math.reduce_std(tf.cast(A, dtype=tf.float64))

(<tf.Tensor: shape=(), dtype=float64, numpy=933.5444000000002>,
 <tf.Tensor: shape=(), dtype=float64, numpy=30.55395882696709>)

In [95]:
# Find the positional maximum and minimum
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.14676988, 0.7232603 , 0.18204689, 0.43902743, 0.6842587 ,
       0.316671  , 0.17261374, 0.1369518 , 0.2174288 , 0.0693053 ,
       0.50952613, 0.35210216, 0.3635081 , 0.06852794, 0.7232897 ,
       0.84380496, 0.22489989, 0.60817385, 0.71819687, 0.30754375,
       0.16279614, 0.18062782, 0.74387693, 0.17787099, 0.6122345 ,
       0.00715911, 0.2142278 , 0.8164208 , 0.5549573 , 0.8607234 ,
       0.26226926, 0.5436449 , 0.29853618, 0.83949995, 0.7564573 ,
       0.41927183, 0.5199864 , 0.603536  , 0.5770047 , 0.9403254 ,
       0.01418662, 0.56805503, 0.69622636, 0.05772936, 0.00203848,
       0.74370694, 0.72286975, 0.46832955, 0.24711645, 0.2501638 ],
      dtype=float32)>

In [99]:
tf.argmax(F), tf.argmin(F), F[tf.argmax(F)], F[tf.argmin(F)]

(<tf.Tensor: shape=(), dtype=int64, numpy=39>,
 <tf.Tensor: shape=(), dtype=int64, numpy=44>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9403254>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.0020384789>)

In [103]:
# Squeezing a tensor
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G.shape, tf.squeeze(G)

(TensorShape([1, 1, 1, 1, 50]),
 <tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.18519199, 0.6754936 , 0.45471764, 0.9613186 , 0.1188941 ,
        0.93939686, 0.3312825 , 0.5516666 , 0.94177926, 0.29517376,
        0.04327619, 0.8428967 , 0.03072119, 0.07530308, 0.5240191 ,
        0.3037176 , 0.9071194 , 0.23251474, 0.25459564, 0.7868885 ,
        0.97144866, 0.9325968 , 0.8594544 , 0.51767576, 0.5289817 ,
        0.01091194, 0.5102725 , 0.53005016, 0.84803843, 0.10250258,
        0.03762138, 0.38383222, 0.73047125, 0.77642405, 0.78390706,
        0.27036572, 0.30315423, 0.12311518, 0.45959675, 0.322438  ,
        0.27677464, 0.3673215 , 0.52192795, 0.28925884, 0.42658532,
        0.9954796 , 0.2750032 , 0.5388402 , 0.5029489 , 0.20404577],
       dtype=float32)>)