<a href="https://colab.research.google.com/github/jescalada/Tensorflow-colabs/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we will cover some fundamental concepts of tensors using TensorFlow 

More specifically, we're going to cover:
* Intro to tensors
* Getting info from tensors
* Manipulating tensors
* Tensors and numpy
* Using @tf.function
* Using GPUs with TF

## Intro to tensors

In [2]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.12.0


In [4]:
# Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [6]:
# Check the number of dimensions of a tensor (ndim - number of dimensions)
scalar.ndim

0

In [11]:
# Create a vector
vector = tf.constant([0,0,255,0,255])
vector

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([  0,   0, 255,   0, 255], dtype=int32)>

In [12]:
vector.ndim

1

In [13]:
matrix = tf.constant([[123, 225],
                      [45, 0]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[123, 225],
       [ 45,   0]], dtype=int32)>

In [14]:
matrix.ndim

2

In [18]:
# Create another matrix
matrix_b = tf.constant([[0.99, 0.01],
                        [0.05, 0.95]], dtype=tf.float16)
matrix_b

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[0.99, 0.01],
       [0.05, 0.95]], dtype=float16)>

In [16]:
matrix_b.ndim

2

In [22]:
# Creating a 3-dim tensor
cube = tf.constant([[
                     [1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]],
                    
                    [[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]],
                    
                    [[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]]])
cube

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]], dtype=int32)>

In [23]:
cube.ndim

3

# Creating tensors with `tf.Variable`

In [25]:
var_tensor = tf.Variable([1, 2, 3])
const_tensor = tf.constant([1, 2, 3])
var_tensor, const_tensor

(<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>)

In [28]:
# Changing the values of a variable tensor
var_tensor = tf.Variable([2, 3, 4])
var_tensor

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([2, 3, 4], dtype=int32)>

In [29]:
var_tensor[0].assign(5)
var_tensor

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([5, 3, 4], dtype=int32)>

In [32]:
# This is not valid!
const_tensor[0].assign(2)

AttributeError: ignored

In [69]:
# Creating random tensors
random_tensor1 = tf.random.Generator.from_seed(123)
random_tensor2 = tf.random.Generator.from_seed(12)
random_tensor3 = tf.random.normal(shape=(3, 1))
random_tensor1, random_tensor2, random_tensor3

(<tensorflow.python.ops.stateful_random_ops.Generator at 0x7f4ed944da90>,
 <tf.Tensor: shape=(3, 1), dtype=float32, numpy=
 array([[ 1.348417  ],
        [-0.12459903],
        [ 0.60070825]], dtype=float32)>)

# Shuffling the order of elements in a tensor

In [73]:
# Shuffling is useful for mixing up the ordering of the data (to make it pseudorandom)
not_shuffled = tf.random.normal(shape=(3, 1))
shuffled = tf.random.shuffle(not_shuffled)
not_shuffled, shuffled

(<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
 array([[ 1.467166  ],
        [ 0.6717987 ],
        [-0.85239375]], dtype=float32)>,
 <tf.Tensor: shape=(3, 1), dtype=float32, numpy=
 array([[-0.85239375],
        [ 0.6717987 ],
        [ 1.467166  ]], dtype=float32)>)

# Creating tensors filled with certain data

In [75]:
# Create a tensor filled with ones
tf.ones((4, 1))

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[1.],
       [1.],
       [1.],
       [1.]], dtype=float32)>

In [76]:
# Create a tensor filled with zeroes
tf.zeros(shape=(3, 3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [79]:
# Turn numpy arrays into tensors
# Tensors can be run in a GPU, unlike numpy arrays
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)  # create a NumPy array with values [1, 25)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [82]:
# Convert the numpy array into a tensor by passing it into the constructor method (takes a tensor-like object)
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [85]:
# We can change the shape of the data without changing the data itself
B = tf.constant(numpy_A, shape=(3, 4, 2))  # This only works if multiplying the dimensions equals 24
B

<tf.Tensor: shape=(3, 4, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]], dtype=int32)>

# Getting info from tensors:
* Shape: The length (number of elements) of each of the dimensions of a tensor
  * `tensor.shape`
* Rank: The number of tensor dimensions. Scalar -> 0, Vector -> 1, etc.
  * `tensor.ndim`
* Axis/Dimension: A particular dimension of a tensor.
  * `tensor[0]`, `tensor[:,1]`, etc.
* Size: The total number of items in the tensor
  * `tf.size(tensor)`

In [90]:
# Creating a rank 4 tensor
rank4tensor = tf.zeros(shape=[2, 2, 2, 4])
rank4tensor

<tf.Tensor: shape=(2, 2, 2, 4), dtype=float32, numpy=
array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]]], dtype=float32)>

In [91]:
rank4tensor.shape, rank4tensor.ndim, tf.size(rank4tensor)  # Note that tf.size returns a scalar tensor

(TensorShape([2, 2, 2, 4]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=32>)